# Generated by Django 3.0.8 on 2020-12-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201110_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_long',
            field=models.CharField(default='', max_length=500),
        ),
    ]
