# Generated by Django 3.0.8 on 2020-12-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201231_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.CharField(default='', max_length=30),
        ),
    ]
