# Generated by Django 3.1.5 on 2021-01-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210101_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_table',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
